### ISSUE TITLE
I think we are missing this method localTime.ToTimeSpanUnspecified()

### ISSUE THREAD

**Issue by arivera12** [nheath99/BlazorNodaTimeDateTimePicker#39]
Time field should be converted to TimeSpan if we are storing our time data on a SQL Time datatype.

**Comment by arivera12** [comment]
This should be as simple as this.
```
TimeSpan ToTimeSpanUnspecified()
{
   return new TimeSpan(localTime.Hour, localTime.Minute, localTime.Second);
}
```

**Comment by nheath99** [comment]
Hi @arivera12,

BlazorNodaTimeDatetimePicker is using NodaTime to repesent and manipulate date/time concepts, and is explicitly not using System.DateTime and System.TimeSpan because of their deficiencies.

Your example is a perfectly acceptable solution, and I would suggest that if you need to convert to TimeSpan in order to store to database then this should not be done in the UI layer.

Nick
